[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["python310", "nodejs"]

[phases.build]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[phases.start]
cmd = "cd backend && python app.py"
